# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180909_0959'),
        ('lists', '0002_list_owner'),
    ]

    operations = [
    ]
